# **Introduction to Tensorflow**

## **What is Tensor?**

+ A tensor is an N-dimensional or multi-dimensional arrays of numbers that represent complex data. 

+ They are the fundamental data structures used in machine learning and deep learning frameworks like TensorFlow and PyTorch.


## **Beginner’s Guide to TensorFlow**

### **Importing TensorFlow**

To get started with TensorFlow, import the library and check its version:

In [74]:
import tensorflow as tf
print(tf.__version__)

import numpy as np
print(np.__version__)

2.15.1
1.26.4


### **1. Setup and Importing Libraries**

You can configure TensorFlow to minimize logging and set GPU memory growth

In [75]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'  # Suppresses TensorFlow warnings
import tensorflow as tf
from tensorflow.python.framework import dtypes

### **2. Checking GPU Availability**

If you have a GPU available, TensorFlow can utilize it. Let’s check and configure it

In [76]:
# Checking GPU Availability
physical_devices = tf.config.list_physical_devices("GPU")
if physical_devices:
    tf.config.experimental.set_memory_growth(physical_devices[0], True)

### **3. Basic Tensor Operations**

#### **Creating Tensors**

Scalar Tensor: A tensor with a single value.

In [77]:
print(tf.constant(5, shape=(), dtype=tf.int16))  # Scalar tensor

tf.Tensor(5, shape=(), dtype=int16)


Matrix Tensors: Creating tensors with specific shapes.

In [78]:
print(tf.ones(shape=(2,2), dtype=tf.int16))
print(tf.zeros(shape=(2,2), dtype=tf.int16))
print(tf.eye(3, dtype=tf.int16))

tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int16)
tf.Tensor(
[[0 0]
 [0 0]], shape=(2, 2), dtype=int16)
tf.Tensor(
[[1 0 0]
 [0 1 0]
 [0 0 1]], shape=(3, 3), dtype=int16)


Random Tensors: Generating tensors with random values.

In [98]:
print(tf.random.normal((3,3), mean=1, stddev=1, dtype=dtypes.float32), "\n")
print(tf.random.uniform((3,3), minval=0, maxval=5))

tf.Tensor(
[[ 2.4355896   1.1195979   0.24019867]
 [ 1.5534406   2.2625694  -0.65558326]
 [ 0.4914506   0.83300495 -0.10441971]], shape=(3, 3), dtype=float32) 

tf.Tensor(
[[0.6636393  2.3590326  2.4731355 ]
 [2.3254073  1.2064445  4.159667  ]
 [0.81051767 2.27095    2.0422025 ]], shape=(3, 3), dtype=float32)


Range Tensors: Creating a tensor with a range of values.

In [80]:
print(tf.range(6))
print(tf.range(start=1, limit=23, delta=3))

tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int32)
tf.Tensor([ 1  4  7 10 13 16 19 22], shape=(8,), dtype=int32)


#### **Casting Tensors**

Type Casting: Changing the data type of a tensor.

In [81]:
x = tf.constant([1.8, 2.2], dtype=tf.float32)
print(tf.dtypes.cast(x, tf.float16))
print(tf.dtypes.cast(x, tf.float32))
print(tf.dtypes.cast(x, tf.float64))

tf.Tensor([1.8 2.2], shape=(2,), dtype=float16)
tf.Tensor([1.8 2.2], shape=(2,), dtype=float32)
tf.Tensor([1.79999995 2.20000005], shape=(2,), dtype=float64)


#### **Tensor Arithmetic**

Basic Arithmetic Operations: Adding, multiplying, and tensor dot product.

In [82]:
x = tf.constant([1, 2, 6])
y = tf.constant([6, 2, 1])
print(tf.add(x, y))  # Element-wise addition
print(x + y)
z = tf.tensordot(a=x, b=y, axes=0)  # Tensor dot product
z = tf.tensordot(a=x, b=y, axes=1)
z = tf.reduce_sum(x * y, axis=0)  # Element-wise multiplication and sum
print(z)
print(tf.constant([1, 2, 6]) ** 2)  # Element-wise power

tf.Tensor([7 4 7], shape=(3,), dtype=int32)
tf.Tensor([7 4 7], shape=(3,), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor([ 1  4 36], shape=(3,), dtype=int32)


#### **Matrix Operations** 

Matrix Multiplication: Multiplying two matrices.

In [83]:
a = tf.constant([[1, 2],[3, 4]])
b = tf.constant([[5, 6], [7, 8]])
result = tf.tensordot(a, b, axes=0)
print("Result with axes=0:\n", result.numpy())

a = tf.random.normal((3, 5))
b = tf.random.normal((5, 6))
z = tf.matmul(a, b)
c = a @ b
print(z, '\n\n\n', c)

Result with axes=0:
 [[[[ 5  6]
   [ 7  8]]

  [[10 12]
   [14 16]]]


 [[[15 18]
   [21 24]]

  [[20 24]
   [28 32]]]]
tf.Tensor(
[[ 0.9358213  -4.8121014   1.7402996  -5.1349573   0.9170374  -1.0839933 ]
 [-1.7571661  -1.8712229   1.0116435  -1.6953175   1.266397    2.7498155 ]
 [ 3.1763268  -0.9387059  -0.15105757 -3.5904245  -1.5653743  -0.8021634 ]], shape=(3, 6), dtype=float32) 


 tf.Tensor(
[[ 0.9358213  -4.8121014   1.7402996  -5.1349573   0.9170374  -1.0839933 ]
 [-1.7571661  -1.8712229   1.0116435  -1.6953175   1.266397    2.7498155 ]
 [ 3.1763268  -0.9387059  -0.15105757 -3.5904245  -1.5653743  -0.8021634 ]], shape=(3, 6), dtype=float32)


### **4. Tensor Slicing and Indexing**

#### **Indexing and Slicing**

Basic Indexing and Slicing:

In [84]:
x = tf.constant([1.8, 2.2, 3.5, 2.2, 2.1, 9.0], dtype=tf.float32)
print(x[1:4])
print(x[::2])
print(x[::-2])

tf.Tensor([2.2 3.5 2.2], shape=(3,), dtype=float32)
tf.Tensor([1.8 3.5 2.1], shape=(3,), dtype=float32)
tf.Tensor([9.  2.2 2.2], shape=(3,), dtype=float32)


Gathering Values:

In [85]:
indices = tf.constant([1, 2])
print(tf.gather(x, indices))

tf.Tensor([2.2 3.5], shape=(2,), dtype=float32)


Multi-dimensional Indexing:

In [86]:
a = tf.constant([[1, 2],[3, 4],[5, 6],[7, 8]])
print(a[3, :])
print(a[1:3, :])
x = tf.range(6)
x = tf.reshape(x, (3, 2))
print(tf.transpose(x, perm=[1, 0]))

tf.Tensor([7 8], shape=(2,), dtype=int32)
tf.Tensor(
[[3 4]
 [5 6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0 2 4]
 [1 3 5]], shape=(2, 3), dtype=int32)


### **5. Introduction to Tensors**

#### **Understanding Tensor Shapes**

Scalars, Vectors, and Matrices:

In [87]:
print(tf.constant(4))  # Scalar
print(tf.constant([2.0, 3.0, 4.0]))  # Vector
print(tf.constant([[1, 2], [3, 4], [5, 6]], dtype=float))  # Matrix

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float32)


Higher Dimensional Tensors:

In [88]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],
])
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


#### **Converting Tensors to NumPy Arrays**

Conversion Methods:

In [89]:
np.array(tf.constant([[1, 2], [3, 4], [5, 6]], dtype=float))
print(tf.constant([[1, 2], [3, 4], [5, 6]], dtype=float).numpy())

[[1. 2.]
 [3. 4.]
 [5. 6.]]


### **6. Tensor Operations**

#### **Basic Math Operations**

Addition, Multiplication, and Matrix Multiplication:

In [90]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[1, 1], [1, 1]])
print(tf.add(a, b))  # Addition
print(tf.multiply(a, b))  # Element-wise multiplication
print(tf.matmul(a, b))  # Matrix multiplication
print(a + b)  # Element-wise addition
print(a * b)  # Element-wise multiplication
print(a @ b)  # Matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


Finding Maximum and Argmax:

In [91]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])
print(tf.reduce_max(c))  # Maximum value
print(tf.math.argmax(c))  # Index of maximum value
print(tf.nn.softmax(c))  # Softmax function

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105854e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


### **7. Tensor Shapes and Reshaping**

#### **Understanding Shapes and Reshaping**

Shape Attributes:

In [92]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])
print("Type of every element:", rank_4_tensor.dtype)
print("Number of dimensions:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of dimensions: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


#### **Reshaping Tensors**

Reshape Operations:

In [99]:
var_x = tf.Variable(tf.constant([[1], [2], [3]]))
print(var_x.shape)
print(var_x.shape.as_list())
reshaped = tf.reshape(var_x, [1, 3])
print(reshaped.shape)

(3, 1)
[3, 1]
(1, 3)


In [100]:
print(tf.reshape(rank_3_tensor, [-1]), "\n")  # Flatten the tensor
print(tf.reshape(rank_3_tensor, [3 * 2, 5]), "\n")
print(tf.reshape(rank_3_tensor, [3, -1]))

tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29], shape=(30,), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)


### **8. Broadcasting**

#### **Understanding Broadcasting**

Broadcasting Basics:

In [95]:
x = tf.constant([1, 2, 3])
y = tf.constant(2)
z = tf.constant([2, 2, 2])
print(tf.multiply(x, 2))
print(x * y)
print(x * z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


Broadcasting in Higher Dimensions:

In [96]:
x = tf.reshape(x, [3, 1])
y = tf.range(1, 5)
print(x, "\n")
print(y, "\n")
print(tf.multiply(x, y))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


Manual Broadcasting

In [97]:
x_stretch = tf.constant([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]])
y_stretch = tf.constant([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]])
print(x_stretch * y_stretch)  # Element-wise multiplication
print(tf.broadcast_to(tf.constant([1, 2, 3]), [3, 3]))

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


This guide covers the basics of TensorFlow and provides a foundation for more advanced topics. Feel free to experiment with these snippets to deepen your understanding of TensorFlow and tensor operations.